# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  schedule:
    - cron:  '*/2 * * * *' # 주기적으로 실행하기 위한 스케줄링 - cron 설정
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
          python-version: '3.x'
          architecture: 'x64'
          
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt         
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run Scraper with python
      run: |
        python "Scraper.py"


    - name: Commits
      run: |
        git config --local user.email "kuick1@daum.net"
        git config --local user.name "Auto_Scraping_Name" # 커밋에 포함될 이름
        git add news.json
        git commit -m "Auto - Update data with Scraping" # 커밋 메세지

